/* This file is autogenerated. DO NOT CHANGE. All changes will be lost */

#ifndef PROTOC2_OPT_AND_REQ_PROPERTIES_QPB_H
#define PROTOC2_OPT_AND_REQ_PROPERTIES_QPB_H

#include <QtProtobuf/qprotobuflazymessagepointer.h>
#include <QtProtobuf/qprotobufmessage.h>
#include <QtProtobuf/qprotobufobject.h>
#include <QtProtobuf/qtprotobuftypes.h>

#include <QtCore/qbytearray.h>
#include <QtCore/qlist.h>
#include <QtCore/qmetatype.h>
#include <QtCore/qshareddata.h>
#include <QtCore/qstring.h>

#include <optional>

class SimpleBoolMessage;
namespace SimpleBoolMessage_QtProtobufNested {
enum class QtProtobufFieldEnum;
} // namespace SimpleBoolMessage_QtProtobufNested

#ifdef QT_USE_PROTOBUF_LIST_ALIASES
using SimpleBoolMessageRepeated = QList<SimpleBoolMessage>;
#endif // QT_USE_PROTOBUF_LIST_ALIASES

class SimpleBoolMessage_QtProtobufData;
class SimpleBoolMessage final : public QProtobufMessage
{
    Q_PROTOBUF_OBJECT
    Q_PROPERTY(bool testReqFieldBool READ testReqFieldBool WRITE setTestReqFieldBool SCRIPTABLE true FINAL)
    Q_PROPERTY(bool testOptFieldBool READ testOptFieldBool_p WRITE setTestOptFieldBool_p FINAL)
    Q_PROPERTY(bool hasTestOptFieldBool READ hasTestOptFieldBool FINAL)
    Q_PROPERTY(QtProtobuf::boolList testRepFieldBool READ testRepFieldBool WRITE setTestRepFieldBool SCRIPTABLE true FINAL)

public:
    using QtProtobufFieldEnum = SimpleBoolMessage_QtProtobufNested::QtProtobufFieldEnum;
    SimpleBoolMessage();
    ~SimpleBoolMessage();
    SimpleBoolMessage(const SimpleBoolMessage &other);
    SimpleBoolMessage &operator =(const SimpleBoolMessage &other);
    SimpleBoolMessage(SimpleBoolMessage &&other) noexcept;
    SimpleBoolMessage &operator =(SimpleBoolMessage &&other) noexcept
    {
        swap(other);
        return *this;
    }
    void swap(SimpleBoolMessage &other) noexcept
    {
        QProtobufMessage::swap(other);
        dptr.swap(other.dptr);
    }
    Q_IMPLICIT operator QVariant() const;

    bool testReqFieldBool() const;

    bool hasTestOptFieldBool() const;
    bool testOptFieldBool() const;

    const QtProtobuf::boolList &testRepFieldBool() const &;
    void setTestReqFieldBool(bool testReqFieldBool);
    void setTestOptFieldBool(bool testOptFieldBool);
    void clearTestOptFieldBool();
    void setTestRepFieldBool(const QtProtobuf::boolList &testRepFieldBool);
    void setTestRepFieldBool(QtProtobuf::boolList &&testRepFieldBool);
    static void registerTypes();

private:
    friend bool comparesEqual(const SimpleBoolMessage &lhs, const SimpleBoolMessage &rhs) noexcept;
    friend bool operator==(const SimpleBoolMessage &lhs, const SimpleBoolMessage &rhs) noexcept
    {
        return comparesEqual(lhs, rhs);
    }
    friend bool operator!=(const SimpleBoolMessage &lhs, const SimpleBoolMessage &rhs) noexcept
    {
        return !comparesEqual(lhs, rhs);
    }
    bool testOptFieldBool_p() const;
    void setTestOptFieldBool_p(bool testOptFieldBool);
    QExplicitlySharedDataPointer<SimpleBoolMessage_QtProtobufData> dptr;
};
namespace SimpleBoolMessage_QtProtobufNested {
Q_NAMESPACE

enum class QtProtobufFieldEnum {
    TestReqFieldBoolProtoFieldNumber = 1,
    TestOptFieldBoolProtoFieldNumber = 2,
    TestRepFieldBoolProtoFieldNumber = 3,
};
Q_ENUM_NS(QtProtobufFieldEnum)

} // namespace SimpleBoolMessage_QtProtobufNested

#endif // PROTOC2_OPT_AND_REQ_PROPERTIES_QPB_H
